# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Basic font for we dev
  - trigger: ":font"
    replace: "-apple-system, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue;"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Email ending
  - trigger: ":br"
    replace: "Best Regards,\nOluwasetemi \nhttps://oluwasetemi.dev"

  # Simple Email Draft
  - trigger: ":email"
    replace: "Hi 👋 , \n\nparagraph 1\n\nparagraph 2\n\nLast Paragraph\n\nBest Regards,\nOluwasetemi\nhttps://oluwasetemi.dev"
